### ISSUE TITLE
Get Prelude to compile

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-in-purescript#26]

**Comment by garyb** [comment]
`Prelude` now compiles, however the other modules in `Prelude.purs` don't, as it doesn't like multiple modules in one file.

I had to do some maybe questionable things to make the parser happy though, because of how the lexer deals with `:`, `<=`, etc: https://github.com/purescript/purescript-in-purescript/blob/4b5db43f826b214f94a9bade28e32b4b41626751/src/Language/PureScript/Parser/Common.purs#L194-L222

**Comment by paf31** [comment]
I think a few of those symbols can safely be excluded since they probably shouldn't be allowed operators anyway, but if it works, then maybe we should just keep them.

**Comment by paf31** [comment]
As for the Prelude, I think we can just break up the modules into individual files now, and we can just include a list of module names in a `Language.PureScript.Prelude` module or something.

**Comment by paf31** [comment]
Heh, I was working on this on the plane, then got off and saw you finished it :)

**Comment by garyb** [comment]
Oops, sorry :) I thought you were looking at `psci`.
